---
title: "UT01 - PROGRAMACIÓN DIDÁCTICA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RESULTADO DE APRENDIZAJE
Reconoce los elementos y herramientas que intervienen en el desarrollo de un programa informático, analizando sus características y las fases en las que actúan hasta llegar a su puesta en funcionamiento. 

# CRITERIOS DE EVALUACIÓN
a) Se ha reconocido la relación de los programas con los componentes del sistema
informático: memoria, procesador, periféricos, entre otros.  
b) Se han identificado las fases de desarrollo de una aplicación informática.  
c) Se han diferenciado los conceptos de código fuente, objeto y ejecutable.  
d) Se han reconocido las características de la generación de código intermedio para su ejecución en máquinas virtuales.  
e) Se han clasificado los lenguajes de programación.  
f) Se ha evaluado la funcionalidad ofrecida por las herramientas utilizadas en
programación. 


# CONTENIDOS
- Concepto de programa informático.
- Instrucciones y datos.
- Ejecución de programas en ordenadores:
   - Datos y programas.
   - Hardware frente a software.
   - Estructura funcional de un ordenador: procesador, memoria.
   - Tipos de software. BIOS. Sistema. Aplicaciones.
   - Código fuente, código objeto y código ejecutable; máquinas
virtuales.
- Lenguajes de programación:
   - Tipos de lenguajes de programación.
   - Características de los lenguajes más difundidos.
- Introducción a la ingeniería del software:
   - Proceso software y ciclo de vida del software.
   - Fases del desarrollo de una aplicación: análisis, diseño, codificación, pruebas, documentación, explotación y mantenimiento, entre otras.
   - Modelos de proceso de desarrollo software (cascada, iterativo, evolutivo).
   - Metodologías de desarrollo software. Características. Técnicas. Objetivos. Tipos de metodologías.
   - Herramientas CASE (Computer Aided Software Engineering).
- Proceso de obtención de código ejecutable a partir del código fuente. 
Herramientas implicadas: editores, compiladores, enlazadores, etc.
- Errores en el desarrollo de programas.
- Importancia de la reutilización de código. 



#### CRITERIOS DE CALFICACIÓN:
| CUADERNO DE CLASE | CUESTIONARIO | EJERCICIOS DE CLASE | PRÁCTICAS |
| -- | -- | -- | -- |
| 20% | 60% | 10% | 10% |



